"""Initial migration.

Revision ID: ed85416a7c4c
Revises: e41cc0fd4d83
Create Date: 2023-12-29 08:23:05.706735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed85416a7c4c'
down_revision = 'e41cc0fd4d83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translate_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('library_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'translate_library', ['library_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translate_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('library_id')

    # ### end Alembic commands ###
